Repository atlanteti/bfree-webui, pull requests merged in 2021-11, with the labels that each got.

#161 Resolve b10t274
  src/Pages/Demandas/Listar/index.js
Labels: feature

#163 resolve b10t273
  src/Componentes/DateField/index.js
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#167 Resolve b10t279
  src/Pages/Log/index.js
Labels: bug

#169 Resolve rejeição do b10t273
  src/Componentes/DateField/index.js
  src/Componentes/DateField/styles.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Demandas/Cadastrar/styles.js
Labels: bug

#170 resolve rejeição da b10t279
  src/Pages/Log/index.js
Labels: bug

#172 Resolve rejeição de b10t274
  src/Componentes/ExclusionModal/index.js
  src/Componentes/IconOverlayMessage/index.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#173 Sobrescrita de função estava sendo aplicada com a assinatura errada
  src/Pages/Demandas/Listar/index.js
Labels: bug

#174 Resolve rejeição de b10t279
  src/Componentes/DateField/index.js
Labels: bug

#179 resolve rejeição de b10t257, agora funcionando com firefox também
  src/Componentes/CustomAlert/index.js
  src/Componentes/ListData/index.js
  src/Pages/Badges/Cadastrar/index.js
  src/Pages/Demandas/Cadastrar/index.js
Labels: bug

#180 Adiciona mensagem enviada pelo servidor a subtexto do campo de entrada,
  src/Componentes/FormFields/index.js
Labels: bug, feature

#181 Adiciona validação e mensagem de erro para seletores de companhia
  src/Componentes/ListCompanies/index.js
  src/Componentes/ListCompaniesControlled/index.js
Labels: bug, feature

#191 Usuário operador pode mover de em aberto para descarte
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#192 Número de caracteres dos campos descrição e observação muda para 400
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#194 Usa o pacote para formatação de data corretamente
  src/Componentes/DateField/index.js
Labels: bug

#195 Inputs são validados quando o botão de submeter é clicado,
  src/Componentes/FormFields/index.js
  src/Pages/Companhia/Cadastrar/Form.js
Labels: feature

#197 Resolve b10t322
  src/Componentes/DefaultValidateInputs/DefaultValidateSelectField.js
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
  src/Componentes/FormFields/index.js
  src/Componentes/ListCompanies/index.js
  src/Pages/Jornadas/Cadastrar/Form.js
Labels: feature

#198 Página de tipo de demanda valida campos
  src/Pages/TipoDemanda/Cadastrar/Form.js
Labels: feature

#199 Remove props defasados
  src/Pages/TipoDemanda/Cadastrar/Form.js
Labels: bug

#200 Resolve b10t325
  src/Componentes/ListCompanies/index.js
  src/Componentes/ListCompaniesControlled/index.js
  src/Componentes/ListJourneysControlled/index.js
  src/Pages/Badges/Cadastrar/Form.js
Labels: feature

#201 Página de times valida campos
  src/Componentes/FormFields/index.js
  src/Pages/Times/Cadastrar/Form.js
Labels: feature

#204 Resolve b10t327
  src/Componentes/ListUserStatus/index.js
  src/Componentes/PhoneInput/index.js
  src/Pages/Usuarios/Cadastrar/Form.js
Labels: feature

#206 Resolve b10t329
  src/Componentes/ActionDatePicker/index.js
  src/Componentes/DefaultValidateInputs/DefaultValidateSelectField.js
  src/Componentes/EditCreateForm/index.js
  src/Componentes/FormFields/index.js
  src/Componentes/ListJourneysControlled/index.js
  src/Componentes/ListStatusDemands/index.js
  src/Componentes/ListTypeDemand/index.js
  src/Componentes/ListUserStatus/index.js
  src/Componentes/ListUsers/index.js
  src/Componentes/PhoneInput/index.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Times/Cadastrar/Form.js
  src/Pages/Usuarios/Cadastrar/Form.js
Labels: bug, documentation, enhancement, feature

#208 b10t331
  src/Pages/Usuarios/Cadastrar/Form.js
Labels: bug

#210 b10t286
  src/styles/CommonStyles.js
Labels: bug

#209 Resolve b10t333
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
  src/Componentes/EditCreateForm/index.js
Labels: bug

#211 Resolve b10t342
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
  src/Componentes/PhoneInput/index.js
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug, documentation, enhancement

#212 B10t340
  src/Componentes/MultiSelectForm/index.js
  src/styles/CommonStyles.js
Labels: enhancement

#214 Feature(Componente): Muda a máscara de acordo com o preenchimento
  src/Componentes/PhoneInput/index.js
Labels: feature

#213 B10t341
  src/Pages/Times/TipoMentores/index.js
Labels: enhancement

#215 b10t346
  src/Componentes/ListCompanies/index.js
Labels: bug

#216 Bug(Componente): Entrada de telefone agora aceita preenchimento vazio
  src/Componentes/PhoneInput/index.js
Labels: bug
