Repository atlanteti/bfree-webui, pull requests merged in 2021-09, with the labels that each got.

#92 Resolve pedido para mudar ação para tipo de log
  src/Pages/Log/index.js
Labels: feature

#95 Resolve o front do ticket 158
  src/App.js
  src/Componentes/CustomMenu/index.js
  src/Componentes/ListData/index.js
  src/Context/AccessPermission.js
  src/Context/ContextLogin.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Demandas/Listar/DemandSearchBar.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#99 Implementa b10t161
  src/Componentes/CustomMenu/index.js
  src/Componentes/ListData/index.js
  src/Pages/Relatorio/Listar/index.js
  src/Routes/auth.routes.js
  src/styles/CommonStyles.js
Labels: feature

#101 Implementa b10t168
  src/Pages/Demandas/Listar/DemandSearchBar.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#102 Alterando campos no formulário de demandas
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#106 Implementa b10t174
  src/Pages/Demandas/Listar/index.js
Labels: bug

#108 Torna campo de status do usuário obrigatório
  src/Componentes/ListUserStatus/index.js
  src/Pages/Usuarios/Cadastrar/Form.js
Labels: enhancement

#109 Alterando icone da aplicação
  public/favicon.ico
Labels: enhancement

#110 Ocultando paginação quando não tiver itens na listagem.
  src/Componentes/ListData/index.js
Labels: bug

#113 Resolve 193
  src/styles/CommonStyles.js
Labels: bug

#114 Resolve 186
  src/Componentes/ListData/index.js
  src/Componentes/SearchBar/index.js
  src/Pages/Demandas/Listar/DemandSearchBar.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#115 Implementando update de permissão do usuário em toda requisição
  src/Context/ContextLogin.js
  src/Services/api.js
Labels: enhancement
