Repository atlanteti/bfree-webui, pull requests merged in 2021-12, with the labels that each got.

#217 B10t348
  src/Componentes/MultiSelectForm/index.js
Labels: enhancement

#218 b10t349
  src/Pages/Usuarios/UsuarioBadges/index.js
  src/Pages/Usuarios/UsuarioCompanhia/index.js
  src/Pages/Usuarios/UsuarioJornadas/index.js
  src/Pages/Usuarios/UsuarioTimes/index.js
  src/Pages/Usuarios/UsuarioTipoDemanda/index.js
Labels: enhancement

#219 Bug(Componente): Campo de telefone alterava formatação de forma errada
  src/Componentes/PhoneInput/index.js
Labels: bug

#220 Resolve b10t330
  package.json
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
  src/Pages/Usuarios/Cadastrar/Form.js
Labels: feature

#221 Resolve rejeição de b10t330
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
  src/Componentes/PhoneInput/index.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Usuarios/Cadastrar/Form.js
  src/Services/validations.js
Labels: bug

#222 B10t351
  src/Pages/Times/TipoMentores/index.js
Labels: enhancement

#224 b10t354
  src/Componentes/CustomFileInputField/index.js
  src/styles/CommonStyles.js
Labels: bug, enhancement

#225 B10t353
  src/Pages/Log/index.js
  src/styles/CommonStyles.js
Labels: feature

#226 Resolve b10t356
  package.json
  src/Componentes/FormikComponents/DatePickerField.js
  src/Componentes/FormikComponents/DefaultValidationTextField.js
  src/Componentes/FormikComponents/GenericFormBuilder.js
  src/Componentes/FormikComponents/GenericSelector.js
  src/Componentes/FormikComponents/ListStatusDemands.js
  src/Componentes/FormikComponents/ListTypeDemand.js
  src/Componentes/FormikComponents/ListUserStatus.js
  src/Componentes/FormikComponents/ListUsers.js
  src/Componentes/FormikComponents/PhoneInput.js
  src/Componentes/FormikComponents/StatusHistory.js
  src/Componentes/FormikComponents/Timestamps.js
Labels: feature

#228 Feat(Service): Adiciona e corrige tradução para campo de email
  src/Services/validations.js
Labels: enhancement

#229 Feat(Componente): Cria o custom hook necessário para rolar a página até um dado elemento
  src/Hooks/index.js
Labels: enhancement, feature

#230 Bug(Componente): Prioriza recebimento de mensagem de campo errado do servidor
  src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
Labels: bug

#231 Feat(Page): Refatora a página de demanda para usar yup e formik
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Demandas/Cadastrar/index.js
Labels: documentation, enhancement, feature

#232 Feat(Page): Refatora a página de demanda para usar yup e formik
  src/Pages/Usuarios/Cadastrar/Form.js
  src/Pages/Usuarios/Cadastrar/index.js
Labels: documentation, enhancement, feature

#227 Refactor(Component): Extrai funcionalidade de rolagem para o componente de alerta
  src/Componentes/CustomAlert/index.js
  src/Componentes/ListData/index.js
  src/Pages/Badges/Cadastrar/index.js
  src/Pages/Demandas/Cadastrar/index.js
Labels: enhancement

#233 Bug(Page): Remove validação de campos desabilitados na edição
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#235 Resolve b10t365
  .env.development
  .env.production
  .env.staging
  package.json
  src/Componentes/ListData/index.js
  src/Componentes/MultiSelectForm/index.js
  src/Pages/Badges/Listar/index.js
  src/Pages/Companhia/Listar/index.js
  src/Pages/Demandas/Listar/index.js
  src/Pages/Jornadas/Listar/index.js
  src/Pages/Times/Listar/index.js
  src/Pages/Times/TipoMentores/index.js
  src/Pages/TipoDemanda/Listar/index.js
  src/Pages/Usuarios/Listar/index.js
  src/Routes/app.routes.js
  src/Routes/auth.routes.js
Labels: enhancement

#237 Bug(Componente): Alerta tenta acessar ref inexistente
  src/Componentes/CustomAlert/index.js
Labels: bug, feature

#238 B10t318
  package.json
  src/Componentes/CustomMenu/index.js
  src/Componentes/Graph/index.js
  src/Pages/Relatorio/Listar/index.js
  src/Pages/RelatorioGerencial/ResultadoSearchBar.js
  src/Pages/RelatorioGerencial/index.js
  src/Routes/auth.routes.js
  src/styles/CommonStyles.js
Labels: enhancement, feature

#239 Bug(CustomMenu): Redirecionamento incompleto no logout
  src/Componentes/CustomMenu/index.js
Labels: bug

#240 B10t371
  src/Componentes/CustomMenu/index.js
  src/Componentes/HourComponent/index.js
  src/Pages/Horarios/index.js
  src/Pages/Horarios/styles.js
  src/Routes/auth.routes.js
Labels: enhancement, feature

#241 Refactor(b10t371)
  src/Pages/Horarios/index.js
Labels: enhancement

#242 b10t373 - Integrar tipos de usuário com página de horário
  src/Componentes/CustomMenu/index.js
  src/Context/ContextLogin.js
  src/Services/api.js
Labels: feature
