Repository atlanteti/bfree-webui, pull requests merged in 2022-01, with the labels that each got.

#243 B10t371
  src/Componentes/HourComponent/index.js
  src/Pages/Horarios/index.js
Labels: bug

#244 b10t357
  src/Hooks/index.js
Labels: enhancement

#245 B10t380
  src/Pages/Usuarios/Listar/UserSearchBar.js
  src/Pages/Usuarios/Listar/index.js
Labels: enhancement

#246 b10t386
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#247 b10t387
  src/Componentes/CustomMenu/index.js
Labels: enhancement

#248 b10t396
  src/Componentes/HourComponent/index.js
  src/Pages/Horarios/index.js
Labels: bug

#250 B10t318
  src/Componentes/CustomMenu/index.js
  src/styles/CommonStyles.js
Labels: enhancement

#252 B10t403
  src/Componentes/ListData/index.js
  src/Componentes/SearchBar/index.js
  src/Pages/Demandas/Listar/DemandSearchBar.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#253 B10t377
  src/Componentes/MeetingCard/index.js
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#254 b10t407
  src/Componentes/CustomMenu/index.js
Labels: enhancement

#251 B10t388
  src/Pages/Avaliacao/index.js
  src/Routes/app.routes.js
  src/Services/api.js
Labels: enhancement, feature

#255 b10t409
  src/Services/api.js
Labels: bug

#257 B10t412
  src/Componentes/CustomMenu/index.js
  src/Componentes/TopBar/index.js
  src/Context/ContextLogin.js
  src/styles/CommonStyles.js
Labels: feature

#258 B10t414
  src/Assets/Icons/icon_badge.svg
  src/Assets/Icons/icon_calendario.svg
  src/Assets/Icons/icon_gerencial.svg
  src/Assets/Icons/icon_logs.svg
  src/Assets/Icons/icon_sair.svg
  src/Assets/Icons/icon_tipos_demandas.svg
  src/Componentes/CustomMenu/index.js
  src/Componentes/CustomMenu/styles.css
Labels: enhancement

#259 b10t415
  src/Pages/Horarios/index.js
Labels: bug

#260 B10t416
  package.json
  src/Context/ContextLogin.js
Labels: bug

#261 Bug(Demand): Resolve erro de mostrar hora da reunião
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#265 b10t427
  src/Pages/RelatorioGerencial/index.js
Labels: enhancement

#263 Resolve b10t423
  src/Pages/Demandas/Listar/index.js
Labels: feature

#264 B10t424
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#266 Resolve b10t431
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#267 Resolve b10t436
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#268 Resolve b10t430
  src/Componentes/ListData/index.js
  src/Pages/Demandas/Listar/index.js
Labels: feature

#270 resolve b10t436
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug
