Repository atlanteti/bfree-webui, pull requests merged in 2022-02, with the labels that each got.

#269 B10t438
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#271 Fix(ListData): Refatora a utilização do grid do bootstap pra resolver espaçamento irregular
  src/Componentes/ListData/index.js
  src/Pages/Relatorio/Listar/index.js
  src/Pages/RelatorioGerencial/index.js
Labels: bug

#272 B10t439
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#273 resolve b10t441
  src/Componentes/ListData/index.js
Labels: bug

#275 fix b10t439
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#276 resolve b10t445
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#279 resolve b10t452
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#280 resolve b10t451
  src/Pages/Demandas/Listar/Contato/index.js
Labels: feature

#282 Feat(Contato pré consultor): Adiciona coluna e permite edição no formulário
  src/Componentes/FormikComponents/ListMessageStatus.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Demandas/Listar/Contato/index.js
Labels: feature

#283 Resolve b10t432
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#284 resolve b10t455
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#285 resolve b10t457
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#287 resolve b10t463
  src/Pages/Demandas/Cadastrar/Form.js
Labels: bug

#288 resolve b10t456
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#289 Resolve b10t459
  package.json
  src/App.js
  src/Componentes/ExclusionModal/index.js
  src/Componentes/ListData/index.js
  src/Componentes/MultiSelectForm/index.js
  src/Pages/Badges/Cadastrar/index.js
  src/Pages/Companhia/Cadastrar/index.js
  src/Pages/Demandas/Cadastrar/Form.js
  src/Pages/Demandas/Cadastrar/index.js
  src/Pages/Jornadas/Cadastrar/index.js
  src/Pages/Times/Cadastrar/index.js
  src/Pages/TipoDemanda/Cadastrar/index.js
  src/Pages/Usuarios/Cadastrar/index.js
Labels: enhancement

#291 Resolve b10t470
  src/App.js
  src/Componentes/CustomMenu/index.js
  src/Context/ContextLogin.js
  src/Pages/Demandas/Listar/index.js
  src/Pages/Termos/index.js
Labels: bug, feature

#292 Fix(CustomMenu/services): Remove menu lateral antigo e ajusta configuração de ambiente
  src/Componentes/CustomMenu/index.js
  src/Services/api.js
Labels: bug

#293 resolve b10t475
  src/Pages/Demandas/Cadastrar/Form.js
Labels: enhancement

#295 Resolve b10t491
  .env.development
  .env.staging
  src/Pages/Demandas/Cadastrar/Form.js
  src/Services/api.js
Labels: feature

#294 resolve b10t462
  src/Componentes/CustomAlert/index.js
  src/Componentes/CustomMenu/index.js
  src/styles/CommonStyles.js
Labels: enhancement, feature

#297 resolve b10t480
  src/Pages/Demandas/Cadastrar/Form.js
Labels: feature

#296 resolve b10t481
  src/Pages/Log/index.js
Labels: enhancement
